version: '2'
services:
  chatdemo1:
    build:
      context: .
      dockerfile: Dockerfile.chatdemo
    image: chatdemo:0.1 
    ports:
     - "8888:8888"
    networks:
      loadtest:
        aliases:
         - chatdemo1


  chatdemo2:
    build:
      context: .
      dockerfile: Dockerfile.chatdemo
    image: chatdemo:0.1
    entrypoint: ["python", "/srv/chatdemo.py", "--port=8889"]
    ports:
     - "8889:8889"
    networks:
      loadtest:
        aliases:
         - chatdemo2


  nginx_api:
    build: ./nginx/
    volumes:
      - ./nginx/chatdemo.template:/etc/nginx/conf.d/chatdemo.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - chatdemo1
      - chatdemo2
    env_file:
      - ./common.env
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/chatdemo.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      loadtest:
        aliases:
         - chatdemo


  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: client:0.1
    depends_on:
      - nginx_api
    environment:
      - WS_URL=ws://chatdemo/chatsocket
      - N_CLIENTS=5000
    networks:
      loadtest:
        aliases:
         - client

networks:
  loadtest:

